### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by L3P3** [LFF5644/site-indexHtml#2]
```
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
    at BatteryService (app.js:26:13)
    at app.js:69:33
```

**Comment by LFF5644** [comment]
könnten sie das genauer beschreiben

**Comment by LFF5644** [comment]
ich habe geguckt dies ist ein einzel fall kein bug oder so

**Comment by L3P3** [comment]
Doch, richtig programmiert würde der Fehler nie auftreten!

**Comment by L3P3** [comment]
Ne, wenn Fehler kommen können, ist das ein BUG. :heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark::heavy_check_mark:

**Comment by LFF5644** [comment]
tya bei mir kommt der bug nicht ist wohl deine browser version von gestern xD

**Comment by L3P3** [comment]
Ne

**Comment by LFF5644** [comment]
doch!

**Comment by L3P3** [comment]
Ne
